version: "3.8"

services:
  api: 
    # image: voltum8/youtube-magnet
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:3000"
    links:
      - redis
  redis:
    image: 'redis:alpine'
    ports:
      - "6379:6379"